[[plugins]]
repo = "Shougo/neocomplete.vim"
depends = "context_filetype.vim"
if = "has('lua')"
on_event = "InsertEnter"
hook_source = """
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
"""

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = "davidhalter/jedi-vim"
if = "!has('nvim')"
on_ft = "python"
hook_source = """
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#smart_auto_mappings = 0
  let g:jedi#show_call_signatures = 0
"""

[[plugins]]
repo = "justmao945/vim-clang"
if = "!has('nvim')"
on_ft = ["c", "cpp"]
hook_source = """
  let g:clang_auto = 0
  let g:clang_cpp_completeopt = "menuone,preview,noinsert"
  let g:clang_exec = "/usr/bin/clang"
  let g:clang_cpp_options = "-std=c++11"
"""
